# Generated by Django 4.2.3 on 2023-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Serie', 'Serie'), ('Pelicula', 'Pelicula')], max_length=20, null=True)),
                ('no_visualizaciones', models.IntegerField(max_length=20)),
                ('puntaje', models.IntegerField(max_length=2)),
            ],
        ),
    ]
