# Generated by Django 4.2.3 on 2023-07-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='puntaje',
            field=models.DecimalField(decimal_places=1, default=5, max_digits=1),
        ),
    ]
