# Generated by Django 4.2.3 on 2023-07-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_peliculas_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='no_visualizaciones',
            field=models.IntegerField(),
        ),
    ]
