# Generated by Django 4.2.3 on 2023-07-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0004_remove_peliculas_puntaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='puntaje',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
