# Generated by Django 4.2.3 on 2023-07-18 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0005_peliculas_puntaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='peliculas',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.genero'),
        ),
    ]
