# Generated by Django 4.2.3 on 2023-07-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_genero_alter_peliculas_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='puntaje',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
