# Generated by Django 4.2.3 on 2023-07-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_alter_peliculas_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peliculas',
            name='no_visualizaciones',
            field=models.IntegerField(default=0),
        ),
    ]
