# Generated by Django 4.2.3 on 2023-07-19 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_remove_usuarios_modelos_usuarios_peliculas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='fecha_incorporacion',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='activo',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='empleado',
            new_name='is_staff',
        ),
    ]
