# Generated by Django 4.2.3 on 2023-07-19 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_genero_alter_peliculas_genero'),
        ('cuentas', '0003_rename_fecha_incorporacion_usuarios_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='peliculas',
        ),
        migrations.CreateModel(
            name='Acciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.peliculas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
