# Generated by Django 4.2.3 on 2023-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0004_remove_usuarios_peliculas_acciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciones',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2),
        ),
    ]
