# Generated by Django 4.2.3 on 2023-07-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0006_genero_alter_peliculas_genero'),
        ('cuentas', '0005_alter_acciones_calificacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='acciones',
            unique_together={('usuario', 'pelicula')},
        ),
    ]
