# Generated by Django 4.2.3 on 2023-07-20 02:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_alter_peliculas_puntaje'),
        ('cuentas', '0006_alter_acciones_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.BooleanField(default=False)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peliculas.peliculas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
