# Generated by Django 4.2.3 on 2023-07-20 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0007_alter_peliculas_puntaje'),
        ('cuentas', '0007_vista'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vista',
            unique_together={('usuario', 'pelicula')},
        ),
    ]
